dashboard_import:
  package_import_url: github://MariuszWoszczynski/wmbus-reader-eth-poe/wmbus-reader-eth-poe-v4.yaml@main
  import_full_config: true

substitutions:
  name: "wmbus-reader-eth-poe-v4"
  friendly_name: "WMBUS Reader ETH POE v4"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: esphome.wmbus_reader_eth
    version: "1.0"

esp32:
  board: esp32-poe
  framework:
    type: arduino


#####  NOTE!!! In the external_components section there is a link to always the latest version of the repository. 
#####  If there will be any changes to the software, user intervention may be required 
#####  (e.g. changing the way sensors are configured, etc.). 
#####  Therefore, it is advisable to follow the information on the site of the author of the software:
#####  https://github.com/SzczepanLeon/esphome-components
external_components:
  - source: github://SzczepanLeon/esphome-components@version_4
    components: [ wmbus ]
    refresh: 0d
    
time:
 - platform: sntp
   id: time_sntp

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "eDNPgLXatKFNoUix14VnAxQ4o+e8YnZVWADNU92wRvo="

ota:
  - platform: esphome

mdns:
  disabled: false
  
web_server: 
  port: 80
  version: 3

ethernet:  
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
#Optional manual IP
#  manual_ip:
#    static_ip: 192.168.10.99
#    gateway: 192.168.10.1
#    subnet: 255.255.255.0

wmbus:    
  mosi_pin: GPIO02
  clk_pin:  GPIO14
  miso_pin: GPIO15
  gdo2_pin: GPIO13
  gdo0_pin: GPIO16
  cs_pin:   GPIO05

  frequency: 868.950
  all_drivers: False
  sync_mode: True
  log_all: True


#  mqtt:
#    broker: 192.168.XX.XX
#    username: xxxxxxxx
#    password: xxxxxxxx

sensor:
###########################################################################################################################################################
###########################################################################################################################################################
# The following sensors are examples, for IZAR, APATOR and UNISMART meters. Leave only the configuration of such meters you have, delete the other sensors. 
# If you have another meter, check its configuration on:  https://github.com/SzczepanLeon/esphome-components
###########################################################################################################################################################
###########################################################################################################################################################


# IZAR water meter
  - platform: wmbus
    meter_id: 0x00000000   ######## enter your IZAR meter ID here ###########
    type: izar
    sensors:
      - name: "RSSI IZAR"
        field: "rssi"
        accuracy_decimals: 0
        unit_of_measurement: "dBm"
        device_class: "signal_strength"
        state_class: "measurement"
        entity_category: "diagnostic"
      - name: "IZAR water meter stater"
        field: "total"
        accuracy_decimals: 3
        unit_of_measurement: "m続"
        device_class: "water"
        state_class: "total_increasing"
        icon: "mdi:water"
      - name: "IZAR Consumption in the last month"
        field: "last_month_total"
        accuracy_decimals: 3
        unit_of_measurement: "m続"
        device_class: "water"
        state_class: "total_increasing"
        icon: "mdi:water"
      - name: "IZAR Transmission period"
        field: "transmit_period"
        accuracy_decimals: 0
        unit_of_measurement: "Second"
      - name: "IZAR Remaining battery life"
        field: "remaining_battery_life"
        accuracy_decimals: 0
        unit_of_measurement: "Year"

# APATOR 16-2 water meter
  - platform: wmbus
    meter_id: 0x00000000     ######## enter your APATOR meter ID here ###########
    type: apator162
    key: "00000000000000000000000000000000"
    sensors:
      - name: "RSSI APATOR"
        field: "rssi"
        accuracy_decimals: 0
        unit_of_measurement: "dBm"
        device_class: "signal_strength"
        state_class: "measurement"
        entity_category: "diagnostic"
      - name: "APATOR water meter state"
        field: "total"
        accuracy_decimals: 3
        unit_of_measurement: "m続"
        device_class: "water"
        state_class: "total_increasing"
        icon: "mdi:water"

# UNISMART gas meter
  - platform: wmbus
    meter_id: 0x00000000        ######## enter your UNISMART meter ID here ###########
    type: unismart
    key: "00000000000000000000000000000000"
    sensors:
      - name: "RSSI UNISMART"
        field: "rssi"
        accuracy_decimals: 0
        unit_of_measurement: "dBm"
        device_class: "signal_strength"
        state_class: "measurement"
        entity_category: "diagnostic"
      - name: "UNISMART gas meter state"
        field: "total"
        accuracy_decimals: 3
        unit_of_measurement: "m続"
        device_class: "gas"
        state_class: "total_increasing"
        icon: "mdi:water"
        #filters:       #optional    
        #  - offset: 991.10   

# AMIPLUS energy meter (eg. OTUS3, GAMA350)
  - platform: wmbus
    meter_id: 0x00000000        ######## enter your AMPIPLUS meter ID here ###########
    type: amiplus
    sensors:
      - name: "My current power consumption"
        field: "current_power_consumption"
        accuracy_decimals: 1
        unit_of_measurement: "w"
        device_class: "power"
        state_class: "measurement"
        icon: "mdi:transmission-tower-import"

      - name: "Total energy consumption"
        field: "total_energy_consumption"
        accuracy_decimals: 3
        unit_of_measurement: "kwh"
        device_class: "energy"
        state_class: "total_increasing"
        icon: "mdi:transmission-tower-import"

      - name: "Total energy consumption on T1"
        field: "total_energy_consumption_tariff_1"
        accuracy_decimals: 3
        unit_of_measurement: "kwh"
        device_class: "energy"
        state_class: "total_increasing"
        icon: "mdi:transmission-tower-import"

      - name: "Total energy consumption on T2"
        field: "total_energy_consumption_tariff_2"
        accuracy_decimals: 3
        unit_of_measurement: "kwh"
        device_class: "energy"
        state_class: "total_increasing"
        icon: "mdi:transmission-tower-import"

      - name: "Total energy consumption on T3"
        field: "total_energy_consumption_tariff_3"
        accuracy_decimals: 3
        unit_of_measurement: "kwh"
        device_class: "energy"
        state_class: "total_increasing"
        icon: "mdi:transmission-tower-import"

      - name: "My current power production"
        field: "current_power_production"
        accuracy_decimals: 1
        unit_of_measurement: "w"
        device_class: "power"
        state_class: "measurement"
        icon: "mdi:transmission-tower-import"

      - name: "Total energy production on T1"
        field: "total_energy_production_tariff_1"
        accuracy_decimals: 3
        unit_of_measurement: "kwh"
        device_class: "energy"
        state_class: "total_increasing"
        icon: "mdi:transmission-tower-import"

      - name: "Total energy production on T2"
        field: "total_energy_production_tariff_2"
        accuracy_decimals: 3
        unit_of_measurement: "kwh"
        device_class: "energy"
        state_class: "total_increasing"
        icon: "mdi:transmission-tower-import"

      - name: "Total energy production on T3"
        field: "total_energy_production_tariff_3"
        accuracy_decimals: 3
        unit_of_measurement: "kwh"
        device_class: "energy"
        state_class: "total_increasing"
        icon: "mdi:transmission-tower-import"

      - name: "Voltage at phase 1"
        field: "voltage_at_phase_1"
        accuracy_decimals: 0
        unit_of_measurement: "v"
        device_class: "voltage"
        state_class: "measurement"
        icon: "mdi:sine-wave"

      - name: "Voltage at phase 2"
        field: "voltage_at_phase_2"
        accuracy_decimals: 0
        unit_of_measurement: "v"
        device_class: "voltage"
        state_class: "measurement"
        icon: "mdi:sine-wave"

      - name: "Voltage at phase 3"
        field: "voltage_at_phase_3"
        accuracy_decimals: 0
        unit_of_measurement: "v"
        device_class: "voltage"
        state_class: "measurement"
        icon: "mdi:sine-wave"
