dashboard_import:
  package_import_url: github://MariuszWoszczynski/wmbus-reader-eth/wmbus-reader-eth-poe.yaml@main
  import_full_config: true

substitutions:
  name: "wmbus-reader-eth"
  friendly_name: "WMBUS Reader ETH POE"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: esphome.wmbus_reader_eth
    version: "1.0"
#  compile_process_limit: 1    # only for RPI 

esp32:
  board: wt32-eth01
  framework:
    type: arduino


external_components:
  - source: github://SzczepanLeon/esphome-components@3.2.3
    components: [ wmbus ]
    refresh: 0d
    
    
time:
 - platform: sntp
   id: time_sntp

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "nq6GQFDVaPbFk9HNVzvtiI+FnePMbnlq3zLv4H1Y/so="

ota:
  - platform: esphome

mdns:
  disabled: false
  
web_server: 
  port: 80

ethernet:  
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  #Optional manual IP
#  manual_ip:
#    static_ip: 192.168.10.220
#    gateway: 192.168.10.1
#    subnet: 255.255.255.0

wmbus:    
  mosi_pin: GPIO02
  clk_pin:  GPIO14
  miso_pin: GPIO15
  gdo2_pin: GPIO13
  gdo0_pin: GPIO16
  cs_pin:   GPIO05
  log_unknown: true


sensor:   
 ############### The following sensors are examples. Adapt the sensors to the meters you have (according to the instructions) and remove the others.###############

# first sensor (water)
  - platform: wmbus
    meter_id: 0x00000000
    type: izar
    add_prefix: false
    lqi:
      name: "My lqi"
    rssi:
      name: "My RSSI"
    total_water_m3:
      name: "My cold water"
   #  filters:              #optional
   #    - offset: 123.4567  #the difference between the indications of the radio overlay and the counter (if you have a used overlay)
    last_month_total_water_m3:
      name: "Last month total water"
    current_month_total_water_l:
      name: "Current month total water"
    transmit_period_s:
      name: "Transmit period [s]"
    remaining_battery_life_y:
      name: "Remaining battery life [Y]"
    current_alarms:
      name: "Current alarms"
    previous_alarms:
      name: "Previous alarms"
  # second sensor (water)
  - platform: wmbus
    meter_id: 0x00000000
    type: apator162
    add_prefix: false
    key: "00000000000000000000000000000000"
    lqi:
      name: "My lqi"
    rssi:
      name: "My RSSI"
    total_water_m3:
      name: "My cold water"
  # third sensor (gas)
  - platform: wmbus
    meter_id: 0x00000000
    type: unismart
    add_prefix: false
    key: "00000000000000000000000000000000"
    lqi:
      name: "My lqi"
    rssi:
      name: "My RSSI"
    total_gas_m3:
      name: "My gas"
  # fourth sensor (electricity)
  - platform: wmbus
    meter_id: 0x00000000
    type: amiplus
    add_prefix: false
    mode: T1C1
    rssi:
      name: "My RSSI"
    total_energy_consumption_kwh:
      name: "My consumption in kWh"
      icon: "mdi:power-plug"
    current_power_consumption_kw:
      name: "My current power consumption in kW"
    total_energy_production_kwh:
      name: "My total energy production in kWh"
    current_power_production_kw:
      name: "My current power production in kW"
    voltage_at_phase_1_v:
      name: "My V1"
    voltage_at_phase_2_v:
      name: "My V2"
    voltage_at_phase_3_v:
      name: "My V3"
  # more options on https://github.com/SzczepanLeon/esphome-components